#!/usr/bin/env sh
# . "$(dirname -- "$0")/_/husky.sh"

# npx --no-install commitlint --edit $1
echo Start running commit-msg hook...
# Check whether the git commit information is standardized
pnpm exec commitlint --edit "$1"

echo Run commit-msg hook done.
